//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ediz_Yurdakul_ST10242585_CLDV6211_POE_Part_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RETURN
    {
        public int RETURN_NO { get; set; }
        public int RENTAL_NO { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public Nullable<int> ELAPSED_DATE { get; set; }
        public Nullable<int> FINE { get; set; }
    
        public virtual TBL_RENTAL TBL_RENTAL { get; set; }
    }
}
