//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ediz_Yurdakul_ST10242585_CLDV6211_POE_Part_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RENTAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_RENTAL()
        {
            this.TBL_RETURN = new HashSet<TBL_RETURN>();
        }
    
        public int RENTAL_NO { get; set; }
        public string CAR_NO { get; set; }
        public string INSPECTOR_NO { get; set; }
        public int DRIVER_NO { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<int> RENTAL_FEE { get; set; }
    
        public virtual TBL_CAR TBL_CAR { get; set; }
        public virtual TBL_DRIVER TBL_DRIVER { get; set; }
        public virtual TBL_INSPECTOR TBL_INSPECTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RETURN> TBL_RETURN { get; set; }
    }
}
