//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ediz_Yurdakul_ST10242585_CLDV6211_POE_Part_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CAR_MODEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CAR_MODEL()
        {
            this.TBL_CAR = new HashSet<TBL_CAR>();
        }
    
        public int CAR_MODEL_ID { get; set; }
        public int CAR_MAKE_ID { get; set; }
        public int CAR_BODYTYPE_ID { get; set; }
        public string CAR_MODEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CAR> TBL_CAR { get; set; }
        public virtual TBL_CAR_BODY_TYPE TBL_CAR_BODY_TYPE { get; set; }
        public virtual TBL_CAR_MAKE TBL_CAR_MAKE { get; set; }
    }
}
