//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ediz_Yurdakul_ST10242585_CLDV6211_POE_Part_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheRideYouRent_Entities : DbContext
    {
        public TheRideYouRent_Entities()
            : base("name=TheRideYouRent_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CAR> TBL_CAR { get; set; }
        public virtual DbSet<TBL_CAR_BODY_TYPE> TBL_CAR_BODY_TYPE { get; set; }
        public virtual DbSet<TBL_CAR_MAKE> TBL_CAR_MAKE { get; set; }
        public virtual DbSet<TBL_CAR_MODEL> TBL_CAR_MODEL { get; set; }
        public virtual DbSet<TBL_DRIVER> TBL_DRIVER { get; set; }
        public virtual DbSet<TBL_INSPECTOR> TBL_INSPECTOR { get; set; }
        public virtual DbSet<TBL_RENTAL> TBL_RENTAL { get; set; }
        public virtual DbSet<TBL_RETURN> TBL_RETURN { get; set; }
    }
}
